# Generated by Django 3.1 on 2022-04-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220309_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text_language',
        ),
        migrations.AddField(
            model_name='comment',
            name='text_language',
            field=models.CharField(default='jp', max_length=8),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='text_language',
        ),
        migrations.AddField(
            model_name='phrase',
            name='text_language',
            field=models.CharField(default='en', max_length=8),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='translated_word_language',
        ),
        migrations.AddField(
            model_name='phrase',
            name='translated_word_language',
            field=models.CharField(default='jp', max_length=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
