# Generated by Django 3.1 on 2022-07-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220705_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='icon/default.png', upload_to='images', verbose_name='アイコン'),
        ),
    ]
