# Generated by Django 3.1 on 2022-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='icons/default.png', upload_to='icons', verbose_name='アイコン'),
        ),
    ]
